# Generated by Django 3.2.9 on 2021-11-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211102_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main_image',
            field=models.BooleanField(default=False),
        ),
    ]
